services:
  - type: web
    name: proctoriax
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k gevent --worker-connections 1000 run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
